#pragma once

#define VOX_SEG_XS 100
#define VOX_SEG_YS 100
#define VOX_HIRES_UNIT 50 // mm
#define VOX_LORES_UNIT 100 // mm

typedef struct
{
	int xmin;
	int xmax;
	int ymin;
	int ymax;
	int reso;
} seg_limits_t;

const seg_limits_t seg_lims[12] =
{
	{	// Seg 0
		0, VOX_SEG_XS*VOX_HIRES_UNIT-1,
		0, VOX_SEG_YS*VOX_HIRES_UNIT-1,
		VOX_HIRES_UNIT
	},

	{	// Seg 1
		-VOX_SEG_XS*VOX_HIRES_UNIT, -1,
		0, VOX_SEG_YS*VOX_HIRES_UNIT-1,
		VOX_HIRES_UNIT
	},

	{	// Seg 2
		-VOX_SEG_XS*VOX_HIRES_UNIT, -1,
		-VOX_SEG_YS*VOX_HIRES_UNIT, -1,
		VOX_HIRES_UNIT
	},

	{	// Seg 3
		0, VOX_SEG_XS*VOX_HIRES_UNIT-1,
		-VOX_SEG_YS*VOX_HIRES_UNIT, -1,
		VOX_HIRES_UNIT
	},

	{	// Seg 4
		VOX_SEG_XS*VOX_HIRES_UNIT, VOX_SEG_XS*VOX_HIRES_UNIT + VOX_SEG_XS*VOX_LORES_UNIT-1,
		-VOX_SEG_YS*VOX_HIRES_UNIT, VOX_SEG_YS*VOX_HIRES_UNIT-1,
		VOX_LORES_UNIT
	},

	{	// Seg 5
		VOX_SEG_XS*VOX_HIRES_UNIT, VOX_SEG_XS*VOX_HIRES_UNIT + VOX_SEG_XS*VOX_LORES_UNIT-1,
		VOX_SEG_YS*VOX_HIRES_UNIT, VOX_SEG_YS*VOX_HIRES_UNIT + VOX_SEG_YS*VOX_LORES_UNIT-1,
		VOX_LORES_UNIT
	},

	{	// Seg 6
		-VOX_SEG_XS*VOX_HIRES_UNIT, VOX_SEG_XS*VOX_HIRES_UNIT-1,
		VOX_SEG_YS*VOX_HIRES_UNIT, VOX_SEG_YS*VOX_HIRES_UNIT + VOX_SEG_YS*VOX_LORES_UNIT-1,
		VOX_LORES_UNIT
	},

	{	// Seg 7
		-VOX_SEG_XS*VOX_HIRES_UNIT - VOX_SEG_XS*VOX_LORES_UNIT, -VOX_SEG_XS*VOX_HIRES_UNIT-1,
		VOX_SEG_YS*VOX_HIRES_UNIT, VOX_SEG_YS*VOX_HIRES_UNIT + VOX_SEG_YS*VOX_LORES_UNIT-1,
		VOX_LORES_UNIT
	},

	{	// Seg 8
		-VOX_SEG_XS*VOX_HIRES_UNIT - VOX_SEG_XS*VOX_LORES_UNIT, -VOX_SEG_XS*VOX_HIRES_UNIT-1,
		-VOX_SEG_YS*VOX_HIRES_UNIT, VOX_SEG_YS*VOX_HIRES_UNIT-1,
		VOX_LORES_UNIT
	},

	{	// Seg 9
		-VOX_SEG_XS*VOX_HIRES_UNIT - VOX_SEG_XS*VOX_LORES_UNIT, -VOX_SEG_XS*VOX_HIRES_UNIT-1,
		-VOX_SEG_YS*VOX_HIRES_UNIT-VOX_SEG_YS*VOX_LORES_UNIT, -VOX_SEG_YS*VOX_HIRES_UNIT-1,
		VOX_LORES_UNIT
	},

	{	// Seg 10
		-VOX_SEG_XS*VOX_HIRES_UNIT, VOX_SEG_XS*VOX_HIRES_UNIT-1,
		-VOX_SEG_YS*VOX_HIRES_UNIT-VOX_SEG_YS*VOX_LORES_UNIT, -VOX_SEG_YS*VOX_HIRES_UNIT-1,
		VOX_LORES_UNIT
	},

	{	// Seg 11
		VOX_SEG_XS*VOX_HIRES_UNIT, VOX_SEG_XS*VOX_HIRES_UNIT + VOX_SEG_XS*VOX_LORES_UNIT-1,
		-VOX_SEG_YS*VOX_HIRES_UNIT-VOX_SEG_YS*VOX_LORES_UNIT, -VOX_SEG_YS*VOX_HIRES_UNIT-1,
		VOX_LORES_UNIT
	}

};

